# Generated by Django 5.0.2 on 2024-03-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcasts',
            old_name='podacst_description',
            new_name='podcast_description',
        ),
    ]
