# Generated by Django 5.0.2 on 2024-03-16 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_login',
            field=models.DateField(default=datetime.date(2024, 3, 16)),
        ),
    ]
