# Generated by Django 5.0.2 on 2024-03-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitymembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymembers',
            old_name='coummunity_id',
            new_name='community_id',
        ),
    ]
