# Generated by Django 5.0.2 on 2024-03-16 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_communitymessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
