# Generated by Django 5.0.2 on 2024-03-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_community_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessages',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
