# Generated by Django 5.0.2 on 2024-03-16 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=255)),
                ('no_of_chapters', models.DecimalField(decimal_places=0, max_digits=2)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=3)),
                ('repeat', models.DecimalField(decimal_places=0, max_digits=2)),
                ('calories', models.DecimalField(decimal_places=0, max_digits=2)),
                ('hashtag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashtags.hashtags')),
            ],
        ),
    ]
