# Generated by Django 5.0.2 on 2024-03-16 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execises', '0002_alter_exercises_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execises.exercises')),
            ],
        ),
    ]
