# Generated by Django 5.0.2 on 2024-03-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execises', '0003_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='long_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='short_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
