# Generated by Django 5.0.2 on 2024-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execises', '0004_exercises_long_img_exercises_short_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='des',
            field=models.CharField(default='', max_length=255),
        ),
    ]
