# Generated by Django 5.0.2 on 2024-03-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execises', '0005_exercises_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
