# Generated by Django 5.0.2 on 2024-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execises', '0006_alter_chapters_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='profile',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
